### ISSUE TITLE
No handler found for the command: 'HookyQR.beautify'

### ISSUE THREAD

**Issue by sbhal** [HookyQR/VSCodeBeautify#1]
I am using beautify 0.0.3 with VSCode 0.10.3 and getting
"No handler found for the command: 'HookyQR.beautify'" warning whenever trying to run Beautify. Extention isn't working as well through it works if I used js-beautify through cmdline.

**Comment by HookyQR** [comment]
This was caused by inclusion of the `"extensionDependencies"` with `"vscode.json"` element in the package file which doesn't exist in **0.10.3**. Removing this dependency doesn't break the functionality in **0.10.5** since it's an internal extension.

Schema doesn't get read in **0.10.3** as `vscode.json` doesn't exist as an extension in that version.

**0.0.4** released.
