### ISSUE TITLE
Please add `ExcludeFile` option or honor .editorconfig better.

### ISSUE THREAD

**Issue by ketonal** [HookyQR/VSCodeBeautify#131]
- VSCode Version: Code 1.11.2 (6eaebe3b9c70406d67c97779468c324a7a95db0e, 2017-04-13T08:03:11.395Z)
- OS Version: Windows_NT ia32 10.0.14393
- Extensions: 

|Extension|Author|Version|
|---|---|---|
|notes-extension|arun92phoenix|0.1.0|
|npm-intellisense|christian-kohler|1.3.0|
|jsrefactor|cmstead|1.0.2|
|vscode-markdownlint|DavidAnson|0.7.1|
|vscode-eslint|dbaeumer|1.2.8|
|githistory|donjayamanne|0.2.0|
|vscode-babel-coloring|dzannotti|0.0.4|
|EditorConfig|EditorConfig|0.9.3|
|tslint|eg2|0.12.0|
|vscode-npm-script|eg2|0.1.9|
|auto-rename-tag|formulahendry|0.0.11|
|beautify|HookyQR|1.0.2|
|docthis|joelday|0.4.3|
|es6-angular-snips|kasperkeso|0.0.3|
|csharp|ms-vscode|1.8.1|
|debugger-for-chrome|msjsdiag|3.0.1|
|vscode-docker|PeterJausovec|0.0.13|
|startanyshell|remcoros|0.3.1|
|json-organizer|rintoj|0.0.3|
|gitblame|waderyan|1.6.0|
|JavaScriptSnippets|xabikos|1.4.0|;

.editorconfig
```
root = true

[*]
indent_style = tab
indent_size = 4

# We recommend you to keep these unchanged
end_of_line = lf
charset = utf-8
trim_trailing_whitespace = true
insert_final_newline = true

[*.md]
trim_trailing_whitespace = false

[package.json]
indent_style = space
indent_size = 2
```
.jsbeautifyrc
```javascript
{
	"indent_size": 0,
	"indent_with_tabs": true,
	"brace_style": "collapse,preserve-inline",
	"keep_array_indentation": true,
	"preserve_newlines": true,
	"max_preserve_newlines": 2,
	"wrap_line_length": 100
}
```

With the settings provided above, whenever I need to manually edit `package.json` file, it's being reformatted. In the docs you're mentioning that you're merging in `.editorconfig`, however, probably not honoring specific files settings. So my request is to kindly add an option to exclude some files from beautifying (even though they match some preliminary patterns), and/or automagically include file-specific config from `.editorconfig`.

**Comment by bijoyanupam** [comment]
I am facing the same issue. Here is my .jsbeautifyrc file.
    {
      "brace_style": "collapse-preserve-inline",
      "max_preserve_newlines": 2,
      "preserve_newlines": true
    }

and my .editorconfig file.

    root = true
    [*]
    indent_style = space
    indent_size = 4
    end_of_line = lf
    trim_trailing_whitespace = true
    insert_final_newline = true

    [package.json]
    indent_size = 2

I need that js-beautify and editorconfig do not conflict for my vscode editor and i get indentation of 2 spaces for my package.json. Neither npm gives any option to configure indentation of package.json file when it writes, and neither .jsbeautifyrc gives option to exclude a file so that indentation can be taken care by .editorconfig file. You know pain :(
Note: I do not want to use vscode settings, because not all my fellow developers use vscode to code.

Is there any option to tackle this issue?

**Comment by HookyQR** [comment]
If a `.jsbeautifyrc` file is found only those settings are used. The editor-config settings are only merged to the VS-Code settings. It seems legit that you should be able to use both. If this is the case the js-beautify settings will override those from the `.editorconfig` file if they conflict.

How would a `mergeEditorConfig` setting suit you? For now at least.

**Comment by ketonal** [comment]
For my scenarion it would be enought if I could just exclude some files either by a full path or a pattern, e.g.:
```
excludeFiles: ["*.md", "./package.json"]
```
However if you're thinking about importing full `.editorconfig` settings then IMO it should do it up to best capabilities of `jsbeautify` - so for every one of the files mentioned in the `.editorconfig` (eg. `[*.md]`) should do exceptional config by joining all the settings from `.jsbeautifyrc` and overriding them by specific values from `.editorconfig`. 
But - I don't know if it wouldn't be too confusing and maybe @bijoyanupam has a better idea?

**Comment by HookyQR** [comment]
added `beautify.ignore` option.

**Comment by bijoyanupam** [comment]
Sorry about the delay in responding...

Ideally, merging the editorconfig into jsbeautify should be best option. And, jsbeautify overriding editorconfig shouldn't be any problem for conflicting items... because, that is intended I believe... when you use jsbeautify config. But, using `beautify.ignore` option is restricted to VSCode users as it requires us to declare the the ignore flag in VScode settings. How do we handle other editors?

**Comment by bijoyanupam** [comment]
@HookyQR if the concern looks legit, please re-open this issue.

**Comment by HookyQR** [comment]
Any change here would only be for VS Code users anyway. I don't own js-beautify, that's a whole other project, I just use it here. js-beautify does have editorconfig support now, but it came after I added it here. I'll take a look at how he's merging options in there (if at all). There are differences with how we handle the `.jsbeautifyrc` file at the moment as well. Will keep you informed.
