### ISSUE TITLE
Full file beautify doubles text on version 1.1.0

### ISSUE THREAD

**Issue by realmx** [HookyQR/VSCodeBeautify#14]
- OS Version: OS X El Capitan 10.11.4
- VSCode Version: 1.1.0-insider
![code](https://cloud.githubusercontent.com/assets/6071313/15010955/bed7cde4-1221-11e6-8c26-b9848be43084.png)

- onSave: false
![false](https://cloud.githubusercontent.com/assets/6071313/15010879/360c9c24-1221-11e6-9427-55491d933b70.gif)

- onSave: true
![true](https://cloud.githubusercontent.com/assets/6071313/15010893/443bc6e4-1221-11e6-92d1-a7b92349df1d.gif)

**Comment by HookyQR** [comment]
Could you please provide an example using some code that is actually modified when the beautify is triggered. This will help to show where the changes are applied. It seems how edits are applied on infinite ranges has been changes in the 1.1 insider.

Since the API is not published for the insiders build, I can't guarantee a fix at this stage.

**Comment by realmx** [comment]
thank you!
