### ISSUE TITLE
<select> tag in HTML is ignored!!!

### ISSUE THREAD

**Issue by AhmedBHameed** [HookyQR/VSCodeBeautify#161]
* **Windows(10)**: 
* **VS Code Version(1.13.1)**: 
* **beautify Version(1.1.1)**: 

Beautify plugin ignore the tag <select></select> when we apply the action. please advice.
![gif](https://user-images.githubusercontent.com/25675361/28076300-82a7c8aa-665e-11e7-81aa-759a6581c6e6.gif)

[Image](https://image.ibb.co/nx6ESv/GIF.gif)

All the settings are the default settings no change has been made.
Thanks a lot.

**Comment by KurtGokhan** [comment]
Tags like select, button and a are unformatted by default. You can configure it to be formatted by excluding it from the configuration in the settings file.


    "beautify.config": {
        "html": {
            "unformatted": [ ... ]
         }
    }

**Comment by AhmedBHameed** [comment]
Thanks @KurtGokhan 
It is a good solution at least make the code organized in a better way. BUT i have a question so why they are by default unformatted ? Also if i do this it means i exclude those tags from getting beatified by the plugin right ??
Is there an explanation behind this ?

**Comment by KurtGokhan** [comment]
@AhmedBHameed 
This extension uses [js-beautify](https://github.com/beautify-web/js-beautify) and default options are defined by that library. Those tags are unformatted by default because formatting it may break your view. For example content of a button tag is displayed as inline and whitespaces sometimes effect the view. A better example would be the pre element where every whitespace counts.

Also, turns out it is better to not use beautify.config but vscode's own config, because if you use beautify.config, beautify will ignore other settings like .editorconfig.

`"html.format.unformatted": "...."`

**Comment by AhmedBHameed** [comment]
Thanks @KurtGokhan  i really appreciate you.
