### ISSUE TITLE
Please, erb files. Please.

### ISSUE THREAD

**Issue by mrkongo** [HookyQR/VSCodeBeautify#33]
How can I help you to support .erb files?

**Comment by HookyQR** [comment]
Beautify should work on `.erb` files as is. `<%` and `%>` are treated as special delimiters. It won't beautify your ruby (in fact it will go out of it's way not to touch it). But it will to the html around it.

Add the following to your settings to always beautify `erb` as `html`:
```javascript
"beautify.HTMLfiles": ["htm", "html", "erb"]
```

It's not in there by default because it doesn't deal with the inner (ruby) parts of the code.

**Comment by mrkongo** [comment]
And for the ruby files? How can I help you?

**Comment by HookyQR** [comment]
Formatting of `.erb` and `.rb` files will eventually be handled by the [ruby extension](https://marketplace.visualstudio.com/items?itemName=rebornix.Ruby). I'm currently working on locating symbol and method definitions for that project. Formatting is on the horizon.
