### ISSUE TITLE
Feature Request: jade beautify

### ISSUE THREAD

**Issue by lamuertepeluda** [HookyQR/VSCodeBeautify#4]
Would it be possible to allow [.jade](http://jade-lang.com/) files formatting as for [jade-beautify](https://atom.io/packages/jade-beautify)?

**Comment by HookyQR** [comment]
I don't use jade myself, but I expect that the inclusion or omission of the `div` tag would be a personal coding choice, rather than something that a beautifier should do for you. Other than that, jade-beautify doesn't seem to do much other than convert spaces to tabs and vice versa. Have a look at the extensions: TabSpacer, WhiteSpacer, and Whitespace for that functionality.

Having said that I think there is potential for a seperate extension for jade, especially given the new previewHtml command available in the 0.10.8 release.
