### ISSUE TITLE
JS - commented out code is indented one extra time

### ISSUE THREAD

**Issue by 11tracer** [HookyQR/VSCodeBeautify#56]
I've run into a small issue with this extension regarding commented-out code. Say I have a block of code like this:

```javascript
const a
const b
// const c
const d
const e
```

Upon running Beautify, it is formatted to look like this:

```javascript
const a
const b
  // const c
const d
const e
```

I don't want the commented code to be indented, I want it to remain in line with the code surrounding it. Is there any way to prevent this behavior?

**Comment by HookyQR** [comment]
Single line comments are considered a part of the current statement. Multi line statements have all additional (not the first) lines indented. Because you haven't closed off the `const b` statement, the comment is considered to be a continuation of that, so it gets an indent. Adding a `;` to close your const declarations (specifically the one before the comment) would un-indent the comment again.
