### ISSUE TITLE
How set short object literals 

### ISSUE THREAD

**Issue by tomoat** [HookyQR/VSCodeBeautify#82]
e.g.:
```js
const reg_query = {
              'ctype': 0,
              'nid': nid,
              'thread': {
                'like': regTitle
              },
              'pid': {
                '>': 0
              },
              'status': {
                '<': 3
              }
            }
console.log(reg_query)
```

Result after executing command now
Present results:

![image](https://cloud.githubusercontent.com/assets/7428698/21501555/d01bd84e-cc83-11e6-81bb-a78bd1ba4de1.png)

I want the results:

![image](https://cloud.githubusercontent.com/assets/7428698/21501523/8f6dbf74-cc83-11e6-934d-dfc81a5c2c71.png)

**Comment by tomoat** [comment]
If the comment is deleted, the result is


![image](https://cloud.githubusercontent.com/assets/7428698/21501620/48c6d050-cc84-11e6-9826-5e01dc1b6753.png)

**Comment by HookyQR** [comment]
If you add the `,preserve-inline` to your `.jsbeautifyrc` `"brace_style"` setting and start with the text formatted the way you want it you may have better luck.

js-beautify doesn't discriminate between braces for object literals and code blocks. You can try using formatting comments before and after the block:
```javascript
/* beautify ignore:start */
const reg_query = {
    'ctype': 0,
    'nid': nid,
    'thread': { 'like': regTitle },
    'pid': { '>': 0 },
    'status': { '<': 3 }
}
/* beautify ignore:end */
```
Unfortunately that won't fix indentation if/when you need it to, so my advise is to use the `,preserve-inline` addition. (I use `"collapse,preserve-inline"`)

Also, I believe the problem with the comment _extra_ indent has been fixed in the latest release.
